name: Chi Sigma Consulting
favicon: null
layout_spectrum: 0.53703
typography_spectrum: 0.6062646133359522
title: Chi Sigma Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8cef3'
    - '#8292ab'
    - '#7d6c50'
    - '#0a3b63'
    - '#180e0c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
