name: Chi Sigma Consulting
favicon: null
layout_spectrum: 0.4106
typography_spectrum: 0.6062646133359522
title: Chi Sigma Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ffc000'
    - '#adadad'
    - '#57678f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
